require_plugin 'ultrasphinx'
require_plugin 'simple_localization'
require_plugin 'acts_as_list'
require_plugin 'acts_as_tree'
require_plugin 'liquid'
require_plugin 'exception_notification'
require_plugin 'annotate_models'
require_plugin 'assert_select'