--- 
javascripts: 
- admin:
  - porthos/prototype
  - porthos/effects
  - porthos/controls
  - porthos/dragdrop
  - porthos/lowpro
  - routes
  - porthos/lib
  - porthos/application
  - porthos/safari_search
- editor:
  - porthos/jquery-1.1.4
  - porthos/wymeditor/lang/sv
  - porthos/wymeditor/jquery.wymeditor
  - porthos/wymeditor/plugins/hovertools/jquery.wymeditor.hovertools
  - porthos/wymeditor/plugins/tidy/jquery.wymeditor.tidy
  - porthos/editor
- pages:
  - porthos/action_dialog
  - porthos/assets
  - porthos/asset_usages
  - porthos/pages
- page_collections:
  - porthos/action_dialog
  - porthos/page_collections
- nodes:
  - porthos/action_dialog
  - porthos/nodes
- assets:
  - porthos/assets
  - porthos/swfobject
  - porthos/mediaplayer
stylesheets: 
- admin:
  - porthos/clearing
  - porthos/general
  - porthos/globals
  - porthos/proxys
  - porthos/pages
  - porthos/nodes
  - porthos/assets
  - porthos/users
  - porthos/activity
  - porthos/wymeditor
- public:
  - basic
  - generic
- print:
  - basic